### ISSUE TITLE
optax.MultiSteps out of memory

### ISSUE THREAD

**Issue by ein-ich** [deepmind/optax#472]
I always get an out of memory error using optax.MultiSteps, even when every_k_schedule=1.
Using optax.apply_every(k=1) in a chain works fine.

```
optimizer = optax.chain(
    optax.clip_by_global_norm(0.5),
    optax.adam(lr),
    #optax.apply_every(k=1)
)
optimizer = optax.MultiSteps(optimizer, every_k_schedule=1)
```
Lalter I'm using
`opt_state = optimizer.init(params)`
and 
```
updates, opt_state = optimizer.update(grads, opt_state, params)
params = optax.apply_updates(params, updates)
```
I have no idea what I could be doing wrong. I'm not changing anything else, like batch size.

**Comment by mkunesch** [comment]
Hi! Interesting - thanks for reporting this!

Are you also at more than ~2/3 memory usage when you use `apply_every`? From a first look, I could see that the implementation of `apply_every` returns `0*updates` for skipped steps while MultiSteps constructs a new array of 0s (even if `every_k_schedule=1`) so the former has a better memory footprint.

I'm not sure why the two functions use completely different code paths - it seems to be that we should be able to merge them (and deprecate one of them).

**Comment by ein-ich** [comment]
I have most of my available memory preallocated by JAX. I tried reducing the batch size from 120 (which works with apply_every) to 30, but it still crashed with MultiSteps.

**Comment by ayaka14732** [comment]
I am training Llama 2 7B on TPU. Without `optax.MultiSteps` my `batch_size` can be 4. However, after applying `optax.MultiSteps`, I got OOM even if `batch_size` is 1.

**Comment by hr0nix** [comment]
I can confirm that MultiStep implementation has much larger memory overhead than just one extra buffer for gradient (something like 4x extra buffers). This is very problematic when using this class with large models.

**Comment by Sea-Snell** [comment]
I also noticed this issue

**Comment by philippe-eecs** [comment]
I am having this issue as well for use in diffusion models

**Comment by agrimgupta92** [comment]
Facing the same issue.

**Comment by hbq1** [comment]
Hi everyone, thanks for flagging it up. I just merged a new version of `optax.MultiSteps` which should be more memory friendly, could you check this please?

**Comment by philippe-eecs** [comment]
you're a king

**Comment by celiolarcher** [comment]
Hi @hbq1! Thank you for the fix! 

One question, I am still seeing a larger consumption with MultiStep when compared with the function apply_every. This was supposed to happen?

**Comment by celiolarcher** [comment]
As a follow-up, I was conducting some debugging by myself and it seems that the problem is on this part of the code (line 414):

```
new_updates, new_state = jax.lax.cond(
          state.mini_step < k_steps - 1,
          _mid_step, _final_step, *(state, params, acc_grads))
```

If I got it right, JAX is allocating memory for both function outputs (_mid_step and _final_step), so this basically doubles the space to store optimizer states and grads.

Still trying to figure out a way to solve it, though.

**Comment by mtthss** [comment]
This is really great!

**Comment by hbq1** [comment]
Awesome work @celiolarcher!

**Comment by celiolarcher** [comment]
I'm glad to be able to help! 
About the issue @hbq1 , I can open it there, no problem.

**Comment by Dashora7** [comment]
I still face this issue when training a Diffusion Policy using Flax 0.11.0 with the nnx.Optimizer class (optax v0.2.5). I observe very slow update step times and memory leaking. When I remove optax.Multisteps and use optax.apply_every(...) in the chain, it fixed the issue. But since apply_every still updates the states of the underlying optimizer for every step (I think), I'd like to have a solution that uses the MultiSteps wrapper. Thanks!

**Comment by rdyro** [comment]
> I still face this issue when training a Diffusion Policy using Flax 0.11.0 with the nnx.Optimizer class (optax v0.2.5). I observe very slow update step times and memory leaking. When I remove optax.Multisteps and use optax.apply_every(...) in the chain, it fixed the issue. But since apply_every still updates the states of the underlying optimizer for every step (I think), I'd like to have a solution that uses the MultiSteps wrapper. Thanks!

Can you be more specific what you mean by memory leaking? Do you have a repro? @Dashora7
